generation:
  paginated_posts: true
  day_archives: false

date_formats:
  month: '%B %Y'

paths:
  archives: 'interviews'
  posts: 'interviews'
  categories: 'categories'

layouts:
  posts: 'interviews'
  category: 'interviews'
  year_archives: 'interviews'
  month_archives: 'interviews'

pagination:
  per_page: 5

category_names:
  bsd: 'BSD'
  mac: 'Macintosh'